# API list for NTDTL app

### Fetch all tickets
GET http://localhost:8000/api/v1/612d714549a44dbd34294682/

### fetch single ticket
GET http://localhost:8000/api/v1/612d714549a44dbd34294682/


### create new ticket
POST  http://localhost:8000/api/v1/
Content-Type:application/json

{
    
    "task":"doing nothing",
    "hr":1
}
### update ticket
PATCH http://localhost:8000/api/v1/
Content-Type:application/json

{
    "_id":"dds",
    "todo":true
}




### delete ticket
DELETE  http://localhost:8000/api/v1
Content-Type:application/json

{
    "_id":"dds",
    
}
