# API list for NTDTL app

### Fetch all tickets
GET http://localhost:8000/api/v1/

### fetch single ticket
GET http://localhost:8000/api/v1/612da48f4c991fefb94c7e7b/


### create new ticket
POST  http://localhost:8000/api/v1/
Content-Type:application/json

{
    
    "task":" nothing",
    "hr":1
}
### update ticket
PATCH http://localhost:8000/api/v1/
Content-Type:application/json

{
    "id":"612eceb3a847a4c74a152202",
    "toDo":true
}




### delete ticket
DELETE  http://localhost:8000/api/v1
Content-Type:application/json

{
    "_id":["612d71b249a44dbd34294684","612d78eb0b2e79144b265b35","612d83329d28463b256a3350"]

    
}

### create user
POST http://localhost:8000/api/v1/user
Content-Type:application/json

{
    "userName": "luit2"
}
