# API list for NTDTL app

### Fetch all tickets
GET http://localhost:8000/api/v1

# ### fetch single ticket
# GET http://localhost:8000/api/v1.ticketId/


### create new ticket
POST  http://localhost:8000/api/v1/
Content-Type:application/json

{
    "email":"dds",
    "password":"cncn"
}



### delete ticket
DELETE  http://localhost:8000/api/v1
